server:
  port: 8080
#spring:
#  application:
#    name: gateway-service #微服务名称
#  profiles:
#    active: dev
#  datasource:
#    url: jdbc:mysql://${hm.db.host}:3306/hmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: ${hm.db.pw}
#  datasource:
#    url: jdbc:mysql://192.168.15.215:3306/hmall?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: z910523.
#  cloud:
#    nacos:
#      server-addr: 192.168.15.215:8848
#    gateway:
#      routes:
#        - id: item
#          uri: lb://item-service
#          predicates:
#            - Path=/items/**,/search/**
#        - id: cart
#          uri: lb://cart-service
#          predicates:
#            - Path=/carts/**
#        - id: user
#          uri: lb://user-service
#          predicates:
#              - Path=/users/**,/addresses/**
#        - id: trade
#          uri: lb://trade-service
#          predicates:
#              - Path=/orders/**
#        - id: pay
#          uri: lb://pay-service
#          predicates:
#              - Path=/pay-orders/**
#
#logging:
#  level:
#    com.hmall: debug
#  pattern:
#    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
hm:
  jwt:
    location: classpath:hmall.jks # 秘钥地址
    alias: hmall # 秘钥别名
    password: hmall123 # 秘钥文件密码
    tokenTTL: 30m # 登录有效期
  auth:
    excludePaths: # 无需登录校验的路径
      - /search/**
      - /users/login
      - /items/**

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123