server:
  port: 8082
  tomcat:
    threads:
      max: 25
    accept-count: 25
    max-connections: 100
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true # 开启feign对sentinel的支持
hm:
  db:
    database: hm-cart
  swagger:
    title: 黑马商城购物车接口文档
    description: 黑马商城购物车接口文档
    email: 1@qq.com
    package: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.15.215:8090 #sentinel
        port: 8719
        client-ip: 192.168.15.235
      http-method-specify: true # 开启请求方式前缀





# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123