server:
  port: 8086

feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-pay
  swagger:
    title: 黑马商城支付接口文档
    description: 黑马支付口文档
    email: 1@qq.com
    package: com.hmall.pay.controller

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123